### ISSUE TITLE
Hey!

### ISSUE THREAD

**Issue by max-circlefade** [SemjonKerner/ampis#1]
Hey @SemjonKerner ! Saw you were working on Rpi and MIDI using Python, that's great! I'm also doing a similar project, me developing a sequencer using a touchscreen.

Would you like to get involved in it ?
Project is CircleFade, you can check our website :)
https://www.circlefade.com/

Thanks! Max

**Comment by SemjonKerner** [comment]
Hey @max-circlefade ,
i want to do everything in C, for it's efficiency. I am working with hardish timings, since i am sampling and replaying midi. I just use python to test functionality, because it's quick and easy. Sadly python has no comprehensive implementation of the ALSA API, which i want to use to some extend.
So the main focus is to get rid of python in the end.

Anyway, i will sure have a look into your project, when i have spare time. So maybe we can help each other out. Thanks for the suggestion!

Also i bought some new LEDs and other Hardware, so pictures will follow. So please come back and take a look :D

**Comment by max-circlefade** [comment]
Ah I see, I was also wondering wether to go with C++ or Python, went for Python because it seems enough to handle just MIDI messages.. we will see, it will be an interesting experience :)

In your project description I see you will use I2C on the Pi, me too so maybe we can give each other some feedback on this while developing.

What I suggest is we connect on FB, will be simpler! https://www.facebook.com/max.circlefade.3

Best regards, Max

**Comment by SemjonKerner** [comment]
I need I2C for the [14 segment display from adafruit](https://www.adafruit.com/product/1911).
I already have the HW at home and might test it over the weekend. I can point you to the python file once it's online. Anyway it will be very device specific except for the protocol overhead, which is probably very well wrapped in python.

**Comment by max-circlefade** [comment]
Nice! Let's keep in touch then :)
